In [ ]:
import numpy as np

In [ ]:
a = [1, 2, 3]
a

In [ ]:
print(a)

In [ ]:
ar1 = np.array(a)
ar1

In [ ]:
print(ar1)

In [ ]:
sen = '파이썬이 쉽니? '
sen

In [ ]:
print(sen)

In [ ]:
type(a)

In [ ]:
type(ar1)

In [ ]:
dir(ar1)

In [ ]:
ar1.shape

In [ ]:
ar1.size

In [ ]:
ar1.dtype

In [ ]:
a = [1, 2.0, '3']
a

In [ ]:
ar1 = np.array(a)
ar1

In [ ]:
ar1.astype(float)

In [ ]:
ar1.astype(int)

In [ ]:
ar1.astype(float).astype(int)

In [ ]:
num = '2.0'

In [ ]:
int(float(num))

In [ ]:
a

In [ ]:
np.array(object = a, dtype = float)

In [ ]:
np.array(object = a, dtype = int)

In [ ]:
np.array(object = a, dtype = str)

In [ ]:
np.array(object = a, dtype = object)

In [ ]:
list(range(6))

In [ ]:
list(range(1, 6))

In [ ]:
list(range(1, 11, 2))

In [ ]:
list(range(0, 1, 0.1))

In [ ]:
np.arange(6)

In [ ]:
np.arange(1, 6)

In [ ]:
np.arange(1, 11, 2)

In [ ]:
np.arange(0, 1, 0.1)

In [ ]:
ar2 = np.arange(0, 1.1, 0.1)

In [ ]:
ar2 = np.round(ar2, 1)
ar2

In [ ]:
for i in ar2:
    print(i)

In [ ]:
%precision 2

In [ ]:
f'{ar2[1]:.2f}'

In [ ]:
ar3 = [f'{i:.2f}' for i in ar2]
ar3

In [ ]:
# 이게 왜 되는 걸까?
[float(i) for i in ar3]

In [ ]:
np.linspace(0, 1, 10+1)

In [ ]:
np.linspace(80, 75, 30+1)

In [ ]:
np.tile(ar1, 2)

In [ ]:
np.repeat(ar1, 2)

In [ ]:
ar1 = np.arange(1, 12, 2)
ar1

In [ ]:
ar1[0]

In [ ]:
ar1[1]

In [ ]:
ar1[-1]

In [ ]:
%precision 3

In [ ]:
a

In [ ]:
a[0]

In [ ]:
a[1]

In [ ]:
a[2]

In [ ]:
ar1[:3]

In [ ]:
ar1[3:]

In [ ]:
ar1[:]

In [ ]:
a[:2]

In [ ]:
a[2:]

In [ ]:
a[:]

In [ ]:
ar1[ [3, 2, 1] ]

In [ ]:
ar1[ [3, 3, 3] ]

In [ ]:
a[ [2, 1] ]

In [ ]:
ar2 = np.array([ [1, 2, 3], [4, 5, 6] ])
ar2

In [ ]:
type(ar2)

In [ ]:
ar2.shape

In [ ]:
ar2.size

In [ ]:
ar2.dtype

In [ ]:
ar1 = np.arange(12)
ar1

In [ ]:
ar1.reshape(4, 3)

In [ ]:
ar1.reshape(4, 3, order = 'F')

In [ ]:
ar2 = ar1.reshape(4, -1)
ar2

In [ ]:
ar2.flatten()

In [ ]:
ar2

In [ ]:
ar2[0, 0]

In [ ]:
ar2[1, 1]

In [ ]:
ar2[0:2, 0:2]

In [ ]:
ar2[:, 1:3]

In [ ]:
ar2[:, [2, 1]]

In [ ]:
ar1 = np.arange(3)
ar1

In [ ]:
ar2 = ar1.reshape(-1, 1)
ar2

In [ ]:
ar1 + 1

In [ ]:
ar2 * 2

In [1]:
import numpy as np
import pandas as pd

In [2]:
ar1 = np.arange(1, 6, 2)
ar1

array([1, 3, 5])

In [3]:
sr = pd.Series(ar1)
sr

0    1
1    3
2    5
dtype: int32

In [4]:
type(sr)

pandas.core.series.Series

In [5]:
sr.shape

(3,)

In [6]:
sr.size

3

In [7]:
sr.dtype

dtype('int32')

In [8]:
sr1 = pd.Series(data = [1, 2.0, '3'], index = ['a', 'b', 'c'])
sr1

a      1
b    2.0
c      3
dtype: object

In [10]:
for i in sr1:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>


In [14]:
sr1.astype(float) + 1

a    2.0
b    3.0
c    4.0
dtype: float64

In [15]:
sr1.astype(str) + '1'

a      11
b    2.01
c      31
dtype: object

In [16]:
pd.Series(data = {'a': 1, 'b': 3, 'c': 5})

a    1
b    3
c    5
dtype: int64

In [17]:
sr

0    1
1    3
2    5
dtype: int32

In [18]:
sr.values

array([1, 3, 5])

In [19]:
sr.index

RangeIndex(start=0, stop=3, step=1)

In [20]:
sr.index = [1, 2, 3]
sr

1    1
2    3
3    5
dtype: int32

In [21]:
sr.index = ['a', 'b', 'c']
sr

a    1
b    3
c    5
dtype: int32

In [22]:
sr

a    1
b    3
c    5
dtype: int32

In [23]:
sr.iloc[[1]]

b    3
dtype: int32

In [24]:
sr

a    1
b    3
c    5
dtype: int32

In [25]:
sr.iloc[0]

1

In [26]:
sr.iloc[[0]]

a    1
dtype: int32

In [27]:
sr.iloc[[0, 2]]

a    1
c    5
dtype: int32

In [28]:
sr.iloc[0:2]

a    1
b    3
dtype: int32

In [29]:
sr

a    1
b    3
c    5
dtype: int32

In [30]:
sr.loc['a']

1

In [31]:
sr.loc[['a']]

a    1
dtype: int32

In [32]:
sr.loc[['a', 'c']]

a    1
c    5
dtype: int32

In [33]:
sr.loc['a':'c']

a    1
b    3
c    5
dtype: int32

In [34]:
sr2 = pd.Series(data = range(3), index = range(1, 4))
sr2

1    0
2    1
3    2
dtype: int64

In [35]:
sr2[0]

KeyError: 0

In [36]:
sr2.loc[1]

0

In [37]:
sr2.iloc[0]

0

In [38]:
sr3 = pd.Series(data = range(3), index = np.tile(1, 3))
sr3

1    0
1    1
1    2
dtype: int64

In [39]:
sr3.loc[1]

1    0
1    1
1    2
dtype: int64

In [40]:
sr3.iloc[0]

0

In [41]:
sr

a    1
b    3
c    5
dtype: int32

In [42]:
sr >= 3

a    False
b     True
c     True
dtype: bool

In [43]:
sr < 5

a     True
b     True
c    False
dtype: bool

In [45]:
(sr >= 3) and (sr < 5)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [46]:
(sr.iloc[0] >= 3) and (sr.iloc[0] < 5)

False

In [48]:
sr >= 3 & sr < 5

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [47]:
(sr >= 3) & (sr < 5)

a    False
b     True
c    False
dtype: bool

In [49]:
(sr >= 3) | (sr < 5)

a    True
b    True
c    True
dtype: bool

In [50]:
(sr >= 3) ^ (sr < 5)

a     True
b    False
c     True
dtype: bool

In [51]:
~ (sr >= 3)

a     True
b    False
c    False
dtype: bool

In [53]:
sr

a    1
b    3
c    5
dtype: int32

In [54]:
sr >= 3

a    False
b     True
c     True
dtype: bool

In [52]:
sr.loc[sr >= 3]

b    3
c    5
dtype: int32

In [55]:
sr.iloc[sr >= 3]

ValueError: iLocation based boolean indexing cannot use an indexable as a mask

In [58]:
sr.loc[(sr >= 3) & (sr < 5)]

b    3
dtype: int32

In [59]:
sr.loc[(sr >= 3) | (sr < 5)]

a    1
b    3
c    5
dtype: int32

In [60]:
sr.loc[~ ((sr >= 3) | (sr < 5))]

Series([], dtype: int32)

In [61]:
sr4 = sr1

In [62]:
id(sr1)

2078927594416

In [63]:
id(sr4)

2078927594416

In [64]:
sr4

a      1
b    2.0
c      3
dtype: object

In [65]:
sr4.iloc[0] = 2

In [66]:
sr4

a      2
b    2.0
c      3
dtype: object

In [67]:
sr1

a      2
b    2.0
c      3
dtype: object

In [68]:
sr5 = sr1.copy()

In [69]:
id(sr1)

2078927594416

In [70]:
id(sr5)

2079242659552

In [71]:
sr5

a      2
b    2.0
c      3
dtype: object

In [72]:
sr5.iloc[0] = 1

In [73]:
sr5

a      1
b    2.0
c      3
dtype: object

In [74]:
sr1

a      2
b    2.0
c      3
dtype: object

In [75]:
ar2 = np.arange(1, 7).reshape(3, -1)
ar2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [76]:
df = pd.DataFrame(ar2)
df

0  1
0  1  2
1  3  4
2  5  6

In [77]:
type(df)

pandas.core.frame.DataFrame

In [78]:
df = pd.DataFrame(data = ar2, index = range(1, 4), columns = ['A', 'B'])
df

A  B
1  1  2
2  3  4
3  5  6

In [79]:
df.shape

(3, 2)

In [80]:
df.dtypes

A    int32
B    int32
dtype: object

In [81]:
df.values

array([[1, 2],
       [3, 4],
       [5, 6]])

In [82]:
df.index

RangeIndex(start=1, stop=4, step=1)

In [83]:
df.columns

Index(['A', 'B'], dtype='object')

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 1 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int32
 1   B       3 non-null      int32
dtypes: int32(2)
memory usage: 156.0 bytes


In [85]:
df

A  B
1  1  2
2  3  4
3  5  6

In [86]:
df.iloc[0]

A    1
B    2
Name: 1, dtype: int32

In [87]:
df.iloc[[0]]

A  B
1  1  2

In [88]:
df.iloc[0:2]

A  B
1  1  2
2  3  4

In [89]:
df.iloc[0:2, :]

A  B
1  1  2
2  3  4

In [90]:
df.iloc[0:2, 0:2]

A  B
1  1  2
2  3  4

In [91]:
df.iloc[:, [1, 0]]

B  A
1  2  1
2  4  3
3  6  5

In [92]:
df

A  B
1  1  2
2  3  4
3  5  6

In [93]:
df.loc[1]

A    1
B    2
Name: 1, dtype: int32

In [94]:
df.loc[[1]]

A  B
1  1  2

In [97]:
df.loc[1:2]

A  B
1  1  2
2  3  4

In [98]:
df.loc[1:2, :]

A  B
1  1  2
2  3  4

In [99]:
df.iloc[0:2, 0:2]

A  B
1  1  2
2  3  4

In [100]:
df.loc[1:2, 'A':'B']

A  B
1  1  2
2  3  4

In [101]:
df.loc[:, ['B', 'A']]

B  A
1  2  1
2  4  3
3  6  5