In [ ]:
sen = ' I am a boy. '
sen

In [ ]:
print(sen)

In [ ]:
sen.strip()

In [ ]:
sen.replace(' ', '')

In [ ]:
name = '홍길동'
rate = 3.2

In [ ]:
name + ' 님의 이자율은 ' + str(rate) + '%입니다.'

In [ ]:
'%s 님의 이자율은 %.2f%%입니다.' %(name, rate)

In [ ]:
'{0} 님의 이자율은 {1:.2f}%입니다.'.format(name, rate)

In [ ]:
f'{name} 님의 이자율은 {rate:.2f}%입니다.'

In [ ]:
import random

In [ ]:
lotto = random.sample(range(1, 46), 6)
lotto

In [ ]:
lotto.sort()

In [ ]:
lotto

In [ ]:
for i in range(10):
    random.seed(1234)
    lotto = random.sample(range(1, 46), 6)
    # lotto.sort(reverse = True)
    lotto.reverse()
    print(lotto)

In [ ]:
a = [1, 2.0, '3']
type(a)

In [ ]:
b = (1, 2.0, '3')
type(b)

In [ ]:
1, 2.0, '3'

In [ ]:
a = list(range(1, 11))
sum(a)

In [ ]:
def sum(x):
    y = 0
    for i in x:
        y -= i
    return(y)

In [ ]:
sum(a)

In [ ]:
del sum

In [ ]:
sum(a)

In [1]:
import numpy as np

In [2]:
a = [1, 2.0, '3']
a

[1, 2.0, '3']

In [3]:
ar1 = np.array(a)
ar1

array(['1', '2.0', '3'], dtype='<U32')

In [4]:
type(ar1)

numpy.ndarray

In [5]:
ar1.shape

(3,)

In [6]:
ar1.size

3

In [7]:
ar1.dtype

dtype('<U32')

In [8]:
ar1.astype(int)

ValueError: invalid literal for int() with base 10: '2.0'

In [9]:
ar1.astype(float)

array([1., 2., 3.])

In [10]:
ar1.astype(float).astype(int)

array([1, 2, 3])

In [11]:
np.array(a, dtype = float)

array([1., 2., 3.])

In [12]:
np.array(a, dtype = int)

array([1, 2, 3])

In [13]:
np.array(a, dtype = str)

array(['1', '2.0', '3'], dtype='<U3')

In [14]:
np.array(a, dtype = object)

array([1, 2.0, '3'], dtype=object)

In [15]:
1 + 1

2

In [16]:
"1" + "1"

'11'

In [17]:
1 + "1"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [19]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [20]:
list(range(1, 6))

[1, 2, 3, 4, 5]

In [21]:
list(range(1, 11, 2))

[1, 3, 5, 7, 9]

In [22]:
list(range(0, 1, 0.1))

TypeError: 'float' object cannot be interpreted as an integer

In [23]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [24]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [25]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [27]:
np.arange(0, 1.1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [28]:
np.linspace(0, 1, 10+1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [29]:
np.linspace(80, 75, 30+1)

array([80.        , 79.83333333, 79.66666667, 79.5       , 79.33333333,
       79.16666667, 79.        , 78.83333333, 78.66666667, 78.5       ,
       78.33333333, 78.16666667, 78.        , 77.83333333, 77.66666667,
       77.5       , 77.33333333, 77.16666667, 77.        , 76.83333333,
       76.66666667, 76.5       , 76.33333333, 76.16666667, 76.        ,
       75.83333333, 75.66666667, 75.5       , 75.33333333, 75.16666667,
       75.        ])

In [30]:
np.tile(ar1, 2)

array(['1', '2.0', '3', '1', '2.0', '3'], dtype='<U32')

In [31]:
np.repeat(ar1, 2)

array(['1', '1', '2.0', '2.0', '3', '3'], dtype='<U32')

In [32]:
ar1 = np.arange(1, 12, 2)
ar1

array([ 1,  3,  5,  7,  9, 11])

In [33]:
ar1[0]

1

In [34]:
ar1[1]

3

In [35]:
ar1[-1]

11

In [36]:
ar1[:3]

array([1, 3, 5])

In [37]:
ar1[3:]

array([ 7,  9, 11])

In [38]:
ar1[:]

array([ 1,  3,  5,  7,  9, 11])

In [39]:
a

[1, 2.0, '3']

In [40]:
a[ [0, 2] ]

TypeError: list indices must be integers or slices, not list

In [41]:
ar1[ [0, 2] ]

array([1, 5])

In [42]:
ar1[ [0] ]

array([1])

In [44]:
ar1[ [0, 0, 0] ]

array([1, 1, 1])

In [45]:
b = [[1, 2, 3], [4, 5, 6]]
b

[[1, 2, 3], [4, 5, 6]]

In [46]:
ar2 = np.array(b)
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
type(ar2)

numpy.ndarray

In [48]:
ar2.shape

(2, 3)

In [49]:
ar2.size

6

In [50]:
ar2.dtype

dtype('int32')

In [51]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [52]:
ar1 = np.arange(12)
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
ar1.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
ar1.reshape(4, 3, order = 'F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [55]:
ar2 = ar1.reshape(4, -1)
ar2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
ar2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])