In [1]:
import os
import chardet
import joblib
import numpy as np
import pandas as pd

In [2]:
os.getcwd()

'C:\\Users\\hdsce\\Documents\\PythonDataAnalysis1\\live'

In [3]:
os.chdir(path = '../data')

In [4]:
os.listdir()

['APT_Detail_Seoul_2022.csv',
 'APT_Detail_Seoul_2022.xlsx',
 'APT_Merged.csv',
 'APT_Merged.xlsx',
 'APT_Price_Prep.z',
 'APT_Price_Seoul_2020.csv',
 'APT_Price_Seoul_2020_2022.csv',
 'APT_Price_Seoul_2020_2022.xlsx',
 'APT_Price_Seoul_2021.csv',
 'APT_Price_Seoul_2022.csv',
 'df1.csv',
 'df2.csv',
 'NA_Sample.xlsx',
 'price.csv']

In [5]:
price, df1, df2 = joblib.load(filename = 'APT_Price_Prep.z')

In [9]:
price.info()

<class 'pandas.core.frame.DataFrame'>
Index: 139917 entries, 0 to 139918
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype         
---  ------  --------------   -----         
 0   아파트     139917 non-null  object        
 1   시       139917 non-null  object        
 2   구       139917 non-null  object        
 3   동       139917 non-null  object        
 4   지번      139917 non-null  object        
 5   건축년도    139917 non-null  float64       
 6   거래일     139917 non-null  datetime64[ns]
 7   전용면적    139917 non-null  float64       
 8   층       139917 non-null  int64         
 9   거래금액    139917 non-null  float64       
 10  평당금액    139917 non-null  float64       
dtypes: datetime64[ns](1), float64(4), int64(1), object(5)
memory usage: 12.8+ MB


In [10]:
price['건축년도'] = price['건축년도'].astype(int)

In [6]:
import sys
sys.version

'3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]'

In [7]:
joblib.__version__

'1.2.0'

In [8]:
os.listdir()

['APT_Detail_Seoul_2022.csv',
 'APT_Detail_Seoul_2022.xlsx',
 'APT_Merged.csv',
 'APT_Merged.xlsx',
 'APT_Price_Prep.z',
 'APT_Price_Seoul_2020.csv',
 'APT_Price_Seoul_2020_2022.csv',
 'APT_Price_Seoul_2020_2022.xlsx',
 'APT_Price_Seoul_2021.csv',
 'APT_Price_Seoul_2022.csv',
 'df1.csv',
 'df2.csv',
 'NA_Sample.xlsx',
 'price.csv']

In [11]:
price = pd.read_csv('price.csv')
df1 = pd.read_csv('df1.csv')
df2 = pd.read_csv('df2.csv')

In [12]:
price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139917 entries, 0 to 139916
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   아파트     139917 non-null  object 
 1   시       139917 non-null  object 
 2   구       139917 non-null  object 
 3   동       139917 non-null  object 
 4   지번      139917 non-null  object 
 5   건축년도    139917 non-null  float64
 6   거래일     139917 non-null  object 
 7   전용면적    139917 non-null  float64
 8   층       139917 non-null  int64  
 9   거래금액    139917 non-null  float64
 10  평당금액    139917 non-null  float64
dtypes: float64(4), int64(1), object(6)
memory usage: 11.7+ MB


In [13]:
price = price.astype(dtype = {'건축년도': int, '거래일': 'datetime64[ns]'})

In [15]:
price['거래년도'] = price['거래일'].dt.year

In [16]:
price['경과년수'] = price['거래년도'] - price['건축년도']

In [17]:
price['거래월'] = price['거래일'].dt.strftime('%m월')

In [18]:
price.head()

아파트      시    구    동      지번  건축년도        거래일    전용면적   층  거래금액   
0     신동아블루아광화문의꿈  서울특별시  종로구  필운동     254  2007 2020-01-03  111.97   6  10.0  \
1  광화문스페이스본(106동)  서울특별시  종로구  사직동     9-1  2008 2020-01-02  163.33   2  16.2   
2           세종로대우  서울특별시  종로구  내수동     167  1994 2020-01-06  109.91  11   8.8   
3            킹스매너  서울특별시  종로구  내수동  110-15  2004 2020-01-09  194.43   4  13.0   
4        경희궁파크팰리스  서울특별시  종로구  내수동      95  2003 2020-01-20  148.09   8  14.9   

          평당금액  거래년도  경과년수  거래월  
0  2947.218005  2020    13  01월  
1  3273.128023  2020    12  01월  
2  2642.161769  2020    26  01월  
3  2206.449622  2020    16  01월  
4  3320.278209  2020    17  01월

In [19]:
locs = price['평당금액'].ge(5000)
locs.head()

0    False
1    False
2    False
3    False
4    False
Name: 평당금액, dtype: bool

In [20]:
price['금액구간'] = np.where(locs, '5천 이상', '5천 미만')

In [21]:
price.head()

아파트      시    구    동      지번  건축년도        거래일    전용면적   층  거래금액   
0     신동아블루아광화문의꿈  서울특별시  종로구  필운동     254  2007 2020-01-03  111.97   6  10.0  \
1  광화문스페이스본(106동)  서울특별시  종로구  사직동     9-1  2008 2020-01-02  163.33   2  16.2   
2           세종로대우  서울특별시  종로구  내수동     167  1994 2020-01-06  109.91  11   8.8   
3            킹스매너  서울특별시  종로구  내수동  110-15  2004 2020-01-09  194.43   4  13.0   
4        경희궁파크팰리스  서울특별시  종로구  내수동      95  2003 2020-01-20  148.09   8  14.9   

          평당금액  거래년도  경과년수  거래월   금액구간  
0  2947.218005  2020    13  01월  5천 미만  
1  3273.128023  2020    12  01월  5천 미만  
2  2642.161769  2020    26  01월  5천 미만  
3  2206.449622  2020    16  01월  5천 미만  
4  3320.278209  2020    17  01월  5천 미만

In [22]:
np.where(locs)

(array([    52,     53,    148, ..., 139900, 139903, 139905], dtype=int64),)

In [23]:
price.head()

아파트      시    구    동      지번  건축년도        거래일    전용면적   층  거래금액   
0     신동아블루아광화문의꿈  서울특별시  종로구  필운동     254  2007 2020-01-03  111.97   6  10.0  \
1  광화문스페이스본(106동)  서울특별시  종로구  사직동     9-1  2008 2020-01-02  163.33   2  16.2   
2           세종로대우  서울특별시  종로구  내수동     167  1994 2020-01-06  109.91  11   8.8   
3            킹스매너  서울특별시  종로구  내수동  110-15  2004 2020-01-09  194.43   4  13.0   
4        경희궁파크팰리스  서울특별시  종로구  내수동      95  2003 2020-01-20  148.09   8  14.9   

          평당금액  거래년도  경과년수  거래월   금액구간  
0  2947.218005  2020    13  01월  5천 미만  
1  3273.128023  2020    12  01월  5천 미만  
2  2642.161769  2020    26  01월  5천 미만  
3  2206.449622  2020    16  01월  5천 미만  
4  3320.278209  2020    17  01월  5천 미만

In [24]:
price['주소'] = price['시'] + ' ' + price['구'] + ' ' \
                + price['동'] + ' ' + price['지번']

In [25]:
price.head()

아파트      시    구    동      지번  건축년도        거래일    전용면적   층  거래금액   
0     신동아블루아광화문의꿈  서울특별시  종로구  필운동     254  2007 2020-01-03  111.97   6  10.0  \
1  광화문스페이스본(106동)  서울특별시  종로구  사직동     9-1  2008 2020-01-02  163.33   2  16.2   
2           세종로대우  서울특별시  종로구  내수동     167  1994 2020-01-06  109.91  11   8.8   
3            킹스매너  서울특별시  종로구  내수동  110-15  2004 2020-01-09  194.43   4  13.0   
4        경희궁파크팰리스  서울특별시  종로구  내수동      95  2003 2020-01-20  148.09   8  14.9   

          평당금액  거래년도  경과년수  거래월   금액구간                    주소  
0  2947.218005  2020    13  01월  5천 미만     서울특별시 종로구 필운동 254  
1  3273.128023  2020    12  01월  5천 미만     서울특별시 종로구 사직동 9-1  
2  2642.161769  2020    26  01월  5천 미만     서울특별시 종로구 내수동 167  
3  2206.449622  2020    16  01월  5천 미만  서울특별시 종로구 내수동 110-15  
4  3320.278209  2020    17  01월  5천 미만      서울특별시 종로구 내수동 95

In [26]:
price.columns

Index(['아파트', '시', '구', '동', '지번', '건축년도', '거래일', '전용면적', '층', '거래금액', '평당금액',
       '거래년도', '경과년수', '거래월', '금액구간', '주소'],
      dtype='object')

In [27]:
cols = ['시', '구', '동', '지번']
price[cols]

시    구    동      지번
0       서울특별시  종로구  필운동     254
1       서울특별시  종로구  사직동     9-1
2       서울특별시  종로구  내수동     167
3       서울특별시  종로구  내수동  110-15
4       서울특별시  종로구  내수동      95
...       ...  ...  ...     ...
139912  서울특별시  강동구  암사동  493-14
139913  서울특별시  강동구  암사동   414-2
139914  서울특별시  강동구  암사동     509
139915  서울특별시  강동구  성내동   452-2
139916  서울특별시  강동구  강일동     114

[139917 rows x 4 columns]

In [28]:
sen = 'I am a boy'

In [30]:
strs = sen.split()
strs

['I', 'am', 'a', 'boy']

In [31]:
' '.join(strs)

'I am a boy'

In [32]:
'-'.join(strs)

'I-am-a-boy'

In [34]:
cols = ['시', '구', '동', '지번']
price[cols]

시    구    동      지번
0       서울특별시  종로구  필운동     254
1       서울특별시  종로구  사직동     9-1
2       서울특별시  종로구  내수동     167
3       서울특별시  종로구  내수동  110-15
4       서울특별시  종로구  내수동      95
...       ...  ...  ...     ...
139912  서울특별시  강동구  암사동  493-14
139913  서울특별시  강동구  암사동   414-2
139914  서울특별시  강동구  암사동     509
139915  서울특별시  강동구  성내동   452-2
139916  서울특별시  강동구  강일동     114

[139917 rows x 4 columns]

In [33]:
price[cols].apply(func = lambda x: ' '.join(x), axis = 1)

0            서울특별시 종로구 필운동 254
1            서울특별시 종로구 사직동 9-1
2            서울특별시 종로구 내수동 167
3         서울특별시 종로구 내수동 110-15
4             서울특별시 종로구 내수동 95
                  ...         
139912    서울특별시 강동구 암사동 493-14
139913     서울특별시 강동구 암사동 414-2
139914       서울특별시 강동구 암사동 509
139915     서울특별시 강동구 성내동 452-2
139916       서울특별시 강동구 강일동 114
Length: 139917, dtype: object

In [35]:
price[cols].apply(func = len, axis = 0)

시     139917
구     139917
동     139917
지번    139917
dtype: int64

In [36]:
price[cols].apply(func = len, axis = 1)

0         4
1         4
2         4
3         4
4         4
         ..
139912    4
139913    4
139914    4
139915    4
139916    4
Length: 139917, dtype: int64

In [37]:
price[cols].apply(func = lambda x: len(x), axis = 0)

시     139917
구     139917
동     139917
지번    139917
dtype: int64

In [39]:
def length(x):
    return len(x)

In [40]:
price[cols].apply(func = length, axis = 0)

시     139917
구     139917
동     139917
지번    139917
dtype: int64

In [41]:
price['아파트']

0            신동아블루아광화문의꿈
1         광화문스페이스본(106동)
2                  세종로대우
3                   킹스매너
4               경희궁파크팰리스
               ...      
139912             중앙하이츠
139913           롯데캐슬퍼스트
139914           선사현대아파트
139915           파크뷰진도맨션
139916         강동리버스트4단지
Name: 아파트, Length: 139917, dtype: object

In [43]:
price['아파트'].map(arg = len).ge(100)

0         False
1         False
2         False
3         False
4         False
          ...  
139912    False
139913    False
139914    False
139915    False
139916    False
Name: 아파트, Length: 139917, dtype: bool

In [45]:
price[cols].applymap(func = len)

시  구  동  지번
0       5  3  3   3
1       5  3  3   3
2       5  3  3   3
3       5  3  3   6
4       5  3  3   2
...    .. .. ..  ..
139912  5  3  3   6
139913  5  3  3   5
139914  5  3  3   3
139915  5  3  3   5
139916  5  3  3   3

[139917 rows x 4 columns]

In [46]:
price['층'].sort_values()

17278     -3
49742     -3
31734     -2
49607     -2
29747     -2
          ..
122507    64
69573     66
110650    66
50867     66
55000     67
Name: 층, Length: 139917, dtype: int64

In [47]:
price['층'].sort_values(ascending = False)

55000     67
110650    66
50867     66
69573     66
137285    64
          ..
49607     -2
45769     -2
52683     -2
17278     -3
49742     -3
Name: 층, Length: 139917, dtype: int64

In [48]:
price.sort_values(by = ['층'])

아파트      시    구    동      지번  건축년도        거래일      전용면적   
17278   은평뉴타운우물골(두산위브7단지)  서울특별시  은평구  진관동      84  2010 2020-03-20  134.5100  \
49742   은평뉴타운우물골(두산위브7단지)  서울특별시  은평구  진관동      84  2010 2020-07-23  134.5100   
31734            롯데캐슬골든힐스  서울특별시  성북구  길음동  1287-1  2019 2020-06-27   59.8946   
49607   은평뉴타운우물골(두산위브7단지)  서울특별시  은평구  진관동      84  2010 2020-07-01  101.9900   
29747     옥수파크힐스101동~116동  서울특별시  성동구  옥수동     528  2016 2020-06-30   76.6600   
...                   ...    ...  ...  ...     ...   ...        ...       ...   
122507             타워팰리스1  서울특별시  강남구  도곡동     467  2002 2021-09-30  222.4800   
69573              타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2020-10-27  185.6220   
110650             타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2021-06-24  214.9670   
50867             현대하이페리온  서울특별시  양천구   목동     916  2003 2020-07-03  154.0500   
55000              타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2020-07-25  235.7400   

         층   거래금액         평당금액  거래년도  경과년수  거래월   금액구간                    주소  
17278   -3   8.20  2011.746339  2020    10  03월  5천 미만      서울특별시 은평구 진관동 84  
49742   -3  10.40  2551.483161  2020    10  07월  5천 미만      서울특별시 은평구 진관동 84  
31734   -2   7.45  4104.710608  2020     1  06월  5천 미만  서울특별시 성북구 길음동 1287-1  
49607   -2   9.47  3064.123934  2020    10  07월  5천 미만      서울특별시 은평구 진관동 84  
29747   -2  16.75  7210.409601  2020     4  06월  5천 이상     서울특별시 성동구 옥수동 528  
...     ..    ...          ...   ...   ...  ...    ...                   ...  
122507  64  48.25  7156.823085  2021    19  09월  5천 이상     서울특별시 강남구 도곡동 467  
69573   66  38.00  6755.664738  2020    16  10월  5천 이상  서울특별시 강남구 도곡동 467-29  
110650  66  45.80  7030.846595  2021    17  06월  5천 이상  서울특별시 강남구 도곡동 467-29  
50867   66  24.00  5141.187926  2020    17  07월  5천 이상      서울특별시 양천구 목동 916  
55000   67  54.25  7594.171545  2020    16  07월  5천 이상  서울특별시 강남구 도곡동 467-29  

[139917 rows x 16 columns]

In [49]:
price.sort_values(by = ['층'], ascending = False)

아파트      시    구    동      지번  건축년도        거래일     전용면적   
55000              타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2020-07-25  235.740  \
110650             타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2021-06-24  214.967   
50867             현대하이페리온  서울특별시  양천구   목동     916  2003 2020-07-03  154.050   
69573              타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2020-10-27  185.622   
137285             타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2022-08-29  244.224   
...                   ...    ...  ...  ...     ...   ...        ...      ...   
49607   은평뉴타운우물골(두산위브7단지)  서울특별시  은평구  진관동      84  2010 2020-07-01  101.990   
45769     옥수파크힐스101동~116동  서울특별시  성동구  옥수동     528  2016 2020-07-30  107.990   
52683           천왕연지타운2단지  서울특별시  구로구  천왕동     281  2014 2020-07-02   84.780   
17278   은평뉴타운우물골(두산위브7단지)  서울특별시  은평구  진관동      84  2010 2020-03-20  134.510   
49742   은평뉴타운우물골(두산위브7단지)  서울특별시  은평구  진관동      84  2010 2020-07-23  134.510   

         층   거래금액         평당금액  거래년도  경과년수  거래월   금액구간                    주소  
55000   67  54.25  7594.171545  2020    16  07월  5천 이상  서울특별시 강남구 도곡동 467-29  
110650  66  45.80  7030.846595  2021    17  06월  5천 이상  서울특별시 강남구 도곡동 467-29  
50867   66  24.00  5141.187926  2020    17  07월  5천 이상      서울특별시 양천구 목동 916  
69573   66  38.00  6755.664738  2020    16  10월  5천 이상  서울특별시 강남구 도곡동 467-29  
137285  64  64.00  8647.798742  2022    18  08월  5천 이상  서울특별시 강남구 도곡동 467-29  
...     ..    ...          ...   ...   ...  ...    ...                   ...  
49607   -2   9.47  3064.123934  2020    10  07월  5천 미만      서울특별시 은평구 진관동 84  
45769   -2  22.00  6722.844708  2020     4  07월  5천 이상     서울특별시 성동구 옥수동 528  
52683   -2   6.77  2635.173390  2020     6  07월  5천 미만     서울특별시 구로구 천왕동 281  
17278   -3   8.20  2011.746339  2020    10  03월  5천 미만      서울특별시 은평구 진관동 84  
49742   -3  10.40  2551.483161  2020    10  07월  5천 미만      서울특별시 은평구 진관동 84  

[139917 rows x 16 columns]

In [50]:
price.sort_values(by = ['층', '거래금액'], ascending = False)

아파트      시    구    동      지번  건축년도        거래일      전용면적   
55000              타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2020-07-25  235.7400  \
110650             타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2021-06-24  214.9670   
69573              타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2020-10-27  185.6220   
50867             현대하이페리온  서울특별시  양천구   목동     916  2003 2020-07-03  154.0500   
137285             타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2022-08-29  244.2240   
...                   ...    ...  ...  ...     ...   ...        ...       ...   
49607   은평뉴타운우물골(두산위브7단지)  서울특별시  은평구  진관동      84  2010 2020-07-01  101.9900   
31734            롯데캐슬골든힐스  서울특별시  성북구  길음동  1287-1  2019 2020-06-27   59.8946   
52683           천왕연지타운2단지  서울특별시  구로구  천왕동     281  2014 2020-07-02   84.7800   
49742   은평뉴타운우물골(두산위브7단지)  서울특별시  은평구  진관동      84  2010 2020-07-23  134.5100   
17278   은평뉴타운우물골(두산위브7단지)  서울특별시  은평구  진관동      84  2010 2020-03-20  134.5100   

         층   거래금액         평당금액  거래년도  경과년수  거래월   금액구간                    주소  
55000   67  54.25  7594.171545  2020    16  07월  5천 이상  서울특별시 강남구 도곡동 467-29  
110650  66  45.80  7030.846595  2021    17  06월  5천 이상  서울특별시 강남구 도곡동 467-29  
69573   66  38.00  6755.664738  2020    16  10월  5천 이상  서울특별시 강남구 도곡동 467-29  
50867   66  24.00  5141.187926  2020    17  07월  5천 이상      서울특별시 양천구 목동 916  
137285  64  64.00  8647.798742  2022    18  08월  5천 이상  서울특별시 강남구 도곡동 467-29  
...     ..    ...          ...   ...   ...  ...    ...                   ...  
49607   -2   9.47  3064.123934  2020    10  07월  5천 미만      서울특별시 은평구 진관동 84  
31734   -2   7.45  4104.710608  2020     1  06월  5천 미만  서울특별시 성북구 길음동 1287-1  
52683   -2   6.77  2635.173390  2020     6  07월  5천 미만     서울특별시 구로구 천왕동 281  
49742   -3  10.40  2551.483161  2020    10  07월  5천 미만      서울특별시 은평구 진관동 84  
17278   -3   8.20  2011.746339  2020    10  03월  5천 미만      서울특별시 은평구 진관동 84  

[139917 rows x 16 columns]

In [51]:
price.sort_values(by = ['층', '거래금액'], ascending = [False, True])

아파트      시    구    동      지번  건축년도        거래일     전용면적   
55000              타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2020-07-25  235.740  \
50867             현대하이페리온  서울특별시  양천구   목동     916  2003 2020-07-03  154.050   
69573              타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2020-10-27  185.622   
110650             타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2021-06-24  214.967   
93843              타워팰리스3  서울특별시  강남구  도곡동  467-29  2004 2021-02-10  214.967   
...                   ...    ...  ...  ...     ...   ...        ...      ...   
49607   은평뉴타운우물골(두산위브7단지)  서울특별시  은평구  진관동      84  2010 2020-07-01  101.990   
29747     옥수파크힐스101동~116동  서울특별시  성동구  옥수동     528  2016 2020-06-30   76.660   
45769     옥수파크힐스101동~116동  서울특별시  성동구  옥수동     528  2016 2020-07-30  107.990   
17278   은평뉴타운우물골(두산위브7단지)  서울특별시  은평구  진관동      84  2010 2020-03-20  134.510   
49742   은평뉴타운우물골(두산위브7단지)  서울특별시  은평구  진관동      84  2010 2020-07-23  134.510   

         층   거래금액         평당금액  거래년도  경과년수  거래월   금액구간                    주소  
55000   67  54.25  7594.171545  2020    16  07월  5천 이상  서울특별시 강남구 도곡동 467-29  
50867   66  24.00  5141.187926  2020    17  07월  5천 이상      서울특별시 양천구 목동 916  
69573   66  38.00  6755.664738  2020    16  10월  5천 이상  서울특별시 강남구 도곡동 467-29  
110650  66  45.80  7030.846595  2021    17  06월  5천 이상  서울특별시 강남구 도곡동 467-29  
93843   64  46.00  7061.548982  2021    17  02월  5천 이상  서울특별시 강남구 도곡동 467-29  
...     ..    ...          ...   ...   ...  ...    ...                   ...  
49607   -2   9.47  3064.123934  2020    10  07월  5천 미만      서울특별시 은평구 진관동 84  
29747   -2  16.75  7210.409601  2020     4  06월  5천 이상     서울특별시 성동구 옥수동 528  
45769   -2  22.00  6722.844708  2020     4  07월  5천 이상     서울특별시 성동구 옥수동 528  
17278   -3   8.20  2011.746339  2020    10  03월  5천 미만      서울특별시 은평구 진관동 84  
49742   -3  10.40  2551.483161  2020    10  07월  5천 미만      서울특별시 은평구 진관동 84  

[139917 rows x 16 columns]

In [52]:
price['거래금액'].count()

139917

In [53]:
price['거래금액'].sum()

1277873.9268999998

In [54]:
price['거래금액'].mean()

9.133085521416268

In [55]:
price['거래금액'].std()

6.747949076315124

In [56]:
price['거래금액'].min()

0.6

In [57]:
price['거래금액'].max()

145.0

In [58]:
price.groupby(by = ['거래년도'])['거래금액'].count()

거래년도
2020    84294
2021    43420
2022    12203
Name: 거래금액, dtype: int64

In [59]:
price.groupby(by = ['거래년도'])['거래금액'].sum()

거래년도
2020    713033.1645
2021    445931.3192
2022    118909.4432
Name: 거래금액, dtype: float64

In [60]:
price.groupby(by = ['거래년도'])['거래금액'].mean()

거래년도
2020     8.458884
2021    10.270182
2022     9.744280
Name: 거래금액, dtype: float64

In [61]:
price.groupby(by = ['거래년도'])['거래금액'].std()

거래년도
2020    5.683750
2021    7.510029
2022    9.495091
Name: 거래금액, dtype: float64

In [62]:
price.groupby(by = ['거래년도'])['거래금액'].min()

거래년도
2020    0.60
2021    0.66
2022    0.67
Name: 거래금액, dtype: float64

In [63]:
price.groupby(by = ['거래년도'])['거래금액'].max()

거래년도
2020     77.5
2021    120.0
2022    145.0
Name: 거래금액, dtype: float64

In [65]:
price.groupby(by = ['구'])['거래금액'].count().sort_values(ascending = False)

구
노원구     13909
강서구      9322
구로구      8491
송파구      7432
성북구      7386
도봉구      6876
강동구      6801
강남구      6723
서초구      6194
영등포구     5998
양천구      5793
은평구      5724
동대문구     5496
중랑구      5089
동작구      5031
성동구      4920
마포구      4849
관악구      4604
서대문구     4558
강북구      3379
금천구      3093
용산구      2685
광진구      2310
중구       1835
종로구      1419
Name: 거래금액, dtype: int64

In [66]:
price.groupby(by = ['구'])['거래금액'].sum().sort_values(ascending = False)

구
강남구     131408.6985
서초구     117312.9891
송파구     103418.8247
노원구      79744.7036
강서구      66239.4481
성동구      62085.3993
강동구      59086.7630
영등포구     55583.6452
양천구      54589.9091
성북구      53973.6943
마포구      51747.7603
동작구      50572.3996
구로구      47930.8031
용산구      46837.4361
동대문구     40136.4651
서대문구     37733.5941
은평구      37693.9124
도봉구      34276.5703
관악구      30179.7642
중랑구      28015.9510
광진구      25564.7715
강북구      19777.2301
중구       16461.1311
금천구      15748.4755
종로구      11753.5876
Name: 거래금액, dtype: float64

In [67]:
price.groupby(by = ['구'])['거래금액'].mean().sort_values(ascending = False)

구
강남구     19.546140
서초구     18.939779
용산구     17.444110
송파구     13.915342
성동구     12.618984
광진구     11.067001
마포구     10.671842
동작구     10.052157
양천구      9.423426
영등포구     9.267030
중구       8.970644
강동구      8.687952
종로구      8.283007
서대문구     8.278542
성북구      7.307568
동대문구     7.302850
강서구      7.105712
은평구      6.585240
관악구      6.555118
강북구      5.852983
노원구      5.733317
구로구      5.644895
중랑구      5.505198
금천구      5.091651
도봉구      4.984958
Name: 거래금액, dtype: float64

In [68]:
price.groupby(by = ['구'])['거래금액'].std().sort_values(ascending = False)

구
용산구     12.617614
강남구     11.641831
서초구     10.951661
성동구      6.444746
송파구      6.368593
종로구      5.545340
영등포구     5.475153
양천구      5.202195
광진구      5.047696
중구       4.726202
마포구      4.338436
강동구      4.288888
동작구      3.948155
서대문구     3.469105
동대문구     3.287190
강서구      3.081141
구로구      2.878946
은평구      2.763860
관악구      2.571511
금천구      2.569918
성북구      2.538690
중랑구      2.323581
노원구      2.177620
강북구      2.131603
도봉구      2.074393
Name: 거래금액, dtype: float64

In [69]:
price.groupby(by = ['구'])['거래금액'].min().sort_values(ascending = False)

구
서초구     1.500
강남구     1.420
송파구     1.395
성동구     1.205
용산구     1.200
마포구     1.140
서대문구    1.100
동작구     1.090
양천구     1.050
성북구     1.000
관악구     0.900
은평구     0.851
중구      0.830
금천구     0.800
강동구     0.780
강서구     0.770
중랑구     0.770
광진구     0.750
강북구     0.750
종로구     0.750
동대문구    0.700
노원구     0.675
영등포구    0.670
도봉구     0.650
구로구     0.600
Name: 거래금액, dtype: float64

In [70]:
price.groupby(by = ['구'])['거래금액'].max().sort_values(ascending = False)

구
강남구     145.00
용산구     135.00
성동구     130.00
서초구      84.00
영등포구     55.50
마포구      51.00
송파구      47.30
동작구      43.00
강동구      40.00
종로구      37.50
중구       37.00
광진구      35.00
양천구      34.15
중랑구      22.00
서대문구     21.50
성북구      21.00
강서구      20.50
구로구      20.50
동대문구     18.30
노원구      18.00
은평구      17.65
관악구      16.00
도봉구      15.00
강북구      14.95
금천구      14.75
Name: 거래금액, dtype: float64

In [73]:
price.groupby(by = ['구', '거래년도'])['거래금액'].count().reset_index()

구  거래년도  거래금액
0   강남구  2020  3718
1   강남구  2021  2252
2   강남구  2022   753
3   강동구  2020  4236
4   강동구  2021  2046
..  ...   ...   ...
70   중구  2021   613
71   중구  2022   194
72  중랑구  2020  2901
73  중랑구  2021  1647
74  중랑구  2022   541

[75 rows x 3 columns]

In [80]:
pd.pivot_table(
    data = price, 
    values = '거래금액', 
    index = ['구', '동'], 
    columns = '거래년도', 
    aggfunc = [np.size, np.mean, np.std]
)

size                     mean                             std   
거래년도      2020   2021   2022       2020       2021       2022      2020   
구   동                                                                     
강남구 개포동  440.0  260.0   62.0  17.807443  21.087132  21.830161  6.250048  \
    논현동  177.0  164.0   74.0  11.496543  12.426288  12.272811  6.610033   
    대치동  386.0  249.0  106.0  22.370284  23.628400  22.713349  9.284923   
    도곡동  569.0  366.0  140.0  21.057678  25.029262  27.188498  8.701096   
    삼성동  303.0  186.0   68.0  15.865716  19.330704  25.452107  9.326685   
...        ...    ...    ...        ...        ...        ...       ...   
중랑구 면목동  692.0  390.0   94.0   4.980918   6.421226   5.337234  1.819639   
    묵동   456.0  249.0   76.0   5.909851   7.132410   5.220658  2.127833   
    상봉동  433.0  211.0  226.0   5.368824   7.195095   4.348186  2.466805   
    신내동  913.0  539.0   81.0   4.883848   6.270315   6.086235  1.495894   
    중화동  188.0  112.0   23.0   5.008245   6.349304   4.272609  1.453030   

                               
거래년도          2021       2022  
구   동                          
강남구 개포동   7.559154  10.046460  
    논현동   8.817302   9.091398  
    대치동  11.963996  14.554145  
    도곡동  12.027377  14.874864  
    삼성동  13.285854  17.519274  
...            ...        ...  
중랑구 면목동   2.736986   3.410288  
    묵동    2.811266   2.978278  
    상봉동   3.256987   2.739573  
    신내동   1.605698   1.857410  
    중화동   1.957695   3.159036  

[332 rows x 9 columns]

In [79]:
pd.pivot_table(
    data = price, 
    values = '거래금액', 
    index = ['구', '동'], 
    columns = '거래년도', 
    aggfunc = [np.size, np.mean, np.std]
).to_excel('pivot_table.xlsx')

In [81]:
price['구'].unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구'], dtype=object)

In [82]:
price['구'].nunique()

25

In [85]:
price.groupby(by = ['구'])['거래금액'].count()

구
강남구      6723
강동구      6801
강북구      3379
강서구      9322
관악구      4604
광진구      2310
구로구      8491
금천구      3093
노원구     13909
도봉구      6876
동대문구     5496
동작구      5031
마포구      4849
서대문구     4558
서초구      6194
성동구      4920
성북구      7386
송파구      7432
양천구      5793
영등포구     5998
용산구      2685
은평구      5724
종로구      1419
중구       1835
중랑구      5089
Name: 거래금액, dtype: int64

In [83]:
price['구'].value_counts()

구
노원구     13909
강서구      9322
구로구      8491
송파구      7432
성북구      7386
도봉구      6876
강동구      6801
강남구      6723
서초구      6194
영등포구     5998
양천구      5793
은평구      5724
동대문구     5496
중랑구      5089
동작구      5031
성동구      4920
마포구      4849
관악구      4604
서대문구     4558
강북구      3379
금천구      3093
용산구      2685
광진구      2310
중구       1835
종로구      1419
Name: count, dtype: int64

In [84]:
price['구'].value_counts().sort_index()

구
강남구      6723
강동구      6801
강북구      3379
강서구      9322
관악구      4604
광진구      2310
구로구      8491
금천구      3093
노원구     13909
도봉구      6876
동대문구     5496
동작구      5031
마포구      4849
서대문구     4558
서초구      6194
성동구      4920
성북구      7386
송파구      7432
양천구      5793
영등포구     5998
용산구      2685
은평구      5724
종로구      1419
중구       1835
중랑구      5089
Name: count, dtype: int64

In [87]:
price['구'].value_counts(normalize = True) * 100

구
노원구     9.940894
강서구     6.662521
구로구     6.068598
송파구     5.311721
성북구     5.278844
도봉구     4.914342
강동구     4.860739
강남구     4.804992
서초구     4.426910
영등포구    4.286827
양천구     4.140312
은평구     4.090997
동대문구    3.928043
중랑구     3.637156
동작구     3.595703
성동구     3.516370
마포구     3.465626
관악구     3.290522
서대문구    3.257646
강북구     2.415003
금천구     2.210596
용산구     1.918995
광진구     1.650979
중구      1.311492
종로구     1.014173
Name: proportion, dtype: float64

In [89]:
price[['구', '동']].value_counts().reset_index()

구      동  count
0    노원구    상계동   5629
1    구로구    구로동   3417
2    노원구    중계동   3003
3    도봉구     창동   2585
4    관악구    봉천동   2475
..   ...    ...    ...
327  용산구  청파동1가      1
328  종로구    누상동      1
329  종로구    옥인동      1
330  종로구    혜화동      1
331  광진구     능동      1

[332 rows x 3 columns]

In [96]:
pd.crosstab(
    index = [price['구'], price['동']], 
    columns = price['거래년도'], 
    margins = True, 
    margins_name = '합계', 
    normalize = 'index'
)

거래년도         2020      2021      2022
구   동                                
강남구 개포동  0.577428  0.341207  0.081365
    논현동  0.426506  0.395181  0.178313
    대치동  0.520918  0.336032  0.143050
    도곡동  0.529302  0.340465  0.130233
    삼성동  0.543986  0.333932  0.122083
...           ...       ...       ...
중랑구 묵동   0.583867  0.318822  0.097311
    상봉동  0.497701  0.242529  0.259770
    신내동  0.595564  0.351598  0.052838
    중화동  0.582043  0.346749  0.071207
합계       0.602457  0.310327  0.087216

[333 rows x 3 columns]

In [97]:
%whos

Variable   Type         Data/Info
---------------------------------
chardet    module       <module 'chardet' from 'C<...>s\\chardet\\__init__.py'>
cols       list         n=4
df1        DataFrame             아파트      시    구 <...>  1450000  \n3  1300000  
df2        DataFrame           아파트      시    구   <...>6-24  214.967  66  458000
joblib     module       <module 'joblib' from 'C:<...>es\\joblib\\__init__.py'>
length     function     <function length at 0x000001AEE1E32200>
locs       Series       0         False\n1       <...>ngth: 139917, dtype: bool
np         module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
os         module       <module 'os' (frozen)>
pd         module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
price      DataFrame                       아파트   <...>139917 rows x 16 columns]
sen        str          I am a boy
strs       list         n=4
sys        module       <module 'sys' (built-in)>


In [98]:
%whos -v DataFrame

Variable   Type         Data/Info
---------------------------------
df1        DataFrame             아파트      시    구 <...>  1450000  \n3  1300000  
df2        DataFrame           아파트      시    구   <...>6-24  214.967  66  458000
price      DataFrame                       아파트   <...>139917 rows x 16 columns]


In [99]:
df1.columns.equals(df2.columns)

True

In [100]:
pd.concat(objs = [df1, df2])

아파트      시    구      동       지번    건축년도         거래일     전용면적   층   
0      파르크한남  서울특별시  용산구    한남동      410  2020.0  2021-12-13  268.950   2  \
1      파르크한남  서울특별시  용산구    한남동      410  2020.0  2022-04-30  268.670   5   
2      PH129  서울특별시  강남구    청담동      129  2020.0  2022-04-28  273.960  16   
3  아크로서울포레스트  서울특별시  성동구  성수동1가  685-700  2020.0  2022-09-30  264.546  47   
0    현대하이페리온  서울특별시  양천구     목동      916  2003.0  2020-07-03  154.050  66   
1     타워팰리스3  서울특별시  강남구    도곡동   467-29  2004.0  2020-07-25  235.740  67   
2     타워팰리스3  서울특별시  강남구    도곡동   467-29  2004.0  2020-10-27  185.622  66   
3     타워팰리스3  서울특별시  강남구    도곡동   467-29  2004.0  2021-06-24  214.967  66   

      거래금액  
0  1200000  
1  1350000  
2  1450000  
3  1300000  
0   240000  
1   542500  
2   380000  
3   458000

In [101]:
pd.concat(objs = [df1, df2], ignore_index = True)

아파트      시    구      동       지번    건축년도         거래일     전용면적   층   
0      파르크한남  서울특별시  용산구    한남동      410  2020.0  2021-12-13  268.950   2  \
1      파르크한남  서울특별시  용산구    한남동      410  2020.0  2022-04-30  268.670   5   
2      PH129  서울특별시  강남구    청담동      129  2020.0  2022-04-28  273.960  16   
3  아크로서울포레스트  서울특별시  성동구  성수동1가  685-700  2020.0  2022-09-30  264.546  47   
4    현대하이페리온  서울특별시  양천구     목동      916  2003.0  2020-07-03  154.050  66   
5     타워팰리스3  서울특별시  강남구    도곡동   467-29  2004.0  2020-07-25  235.740  67   
6     타워팰리스3  서울특별시  강남구    도곡동   467-29  2004.0  2020-10-27  185.622  66   
7     타워팰리스3  서울특별시  강남구    도곡동   467-29  2004.0  2021-06-24  214.967  66   

      거래금액  
0  1200000  
1  1350000  
2  1450000  
3  1300000  
4   240000  
5   542500  
6   380000  
7   458000

In [102]:
df2 = df2.rename(columns = {'아파트': '아파트명'})

In [103]:
df1.columns.equals(df2.columns)

False

In [104]:
pd.concat(objs = [df1, df2], ignore_index = True)

아파트      시    구      동       지번    건축년도         거래일     전용면적   층   
0      파르크한남  서울특별시  용산구    한남동      410  2020.0  2021-12-13  268.950   2  \
1      파르크한남  서울특별시  용산구    한남동      410  2020.0  2022-04-30  268.670   5   
2      PH129  서울특별시  강남구    청담동      129  2020.0  2022-04-28  273.960  16   
3  아크로서울포레스트  서울특별시  성동구  성수동1가  685-700  2020.0  2022-09-30  264.546  47   
4        NaN  서울특별시  양천구     목동      916  2003.0  2020-07-03  154.050  66   
5        NaN  서울특별시  강남구    도곡동   467-29  2004.0  2020-07-25  235.740  67   
6        NaN  서울특별시  강남구    도곡동   467-29  2004.0  2020-10-27  185.622  66   
7        NaN  서울특별시  강남구    도곡동   467-29  2004.0  2021-06-24  214.967  66   

      거래금액     아파트명  
0  1200000      NaN  
1  1350000      NaN  
2  1450000      NaN  
3  1300000      NaN  
4   240000  현대하이페리온  
5   542500   타워팰리스3  
6   380000   타워팰리스3  
7   458000   타워팰리스3

In [105]:
df3 = df2.copy()

In [106]:
pd.concat(objs = [df1, df2, df3], ignore_index = True)

아파트      시    구      동       지번    건축년도         거래일     전용면적   층   
0       파르크한남  서울특별시  용산구    한남동      410  2020.0  2021-12-13  268.950   2  \
1       파르크한남  서울특별시  용산구    한남동      410  2020.0  2022-04-30  268.670   5   
2       PH129  서울특별시  강남구    청담동      129  2020.0  2022-04-28  273.960  16   
3   아크로서울포레스트  서울특별시  성동구  성수동1가  685-700  2020.0  2022-09-30  264.546  47   
4         NaN  서울특별시  양천구     목동      916  2003.0  2020-07-03  154.050  66   
5         NaN  서울특별시  강남구    도곡동   467-29  2004.0  2020-07-25  235.740  67   
6         NaN  서울특별시  강남구    도곡동   467-29  2004.0  2020-10-27  185.622  66   
7         NaN  서울특별시  강남구    도곡동   467-29  2004.0  2021-06-24  214.967  66   
8         NaN  서울특별시  양천구     목동      916  2003.0  2020-07-03  154.050  66   
9         NaN  서울특별시  강남구    도곡동   467-29  2004.0  2020-07-25  235.740  67   
10        NaN  서울특별시  강남구    도곡동   467-29  2004.0  2020-10-27  185.622  66   
11        NaN  서울특별시  강남구    도곡동   467-29  2004.0  2021-06-24  214.967  66   

       거래금액     아파트명  
0   1200000      NaN  
1   1350000      NaN  
2   1450000      NaN  
3   1300000      NaN  
4    240000  현대하이페리온  
5    542500   타워팰리스3  
6    380000   타워팰리스3  
7    458000   타워팰리스3  
8    240000  현대하이페리온  
9    542500   타워팰리스3  
10   380000   타워팰리스3  
11   458000   타워팰리스3

In [108]:
pd.concat(objs = [df1, df2], axis = 1)

아파트      시    구      동       지번    건축년도         거래일     전용면적   층   
0      파르크한남  서울특별시  용산구    한남동      410  2020.0  2021-12-13  268.950   2  \
1      파르크한남  서울특별시  용산구    한남동      410  2020.0  2022-04-30  268.670   5   
2      PH129  서울특별시  강남구    청담동      129  2020.0  2022-04-28  273.960  16   
3  아크로서울포레스트  서울특별시  성동구  성수동1가  685-700  2020.0  2022-09-30  264.546  47   

      거래금액     아파트명      시    구    동      지번    건축년도         거래일     전용면적   층   
0  1200000  현대하이페리온  서울특별시  양천구   목동     916  2003.0  2020-07-03  154.050  66  \
1  1350000   타워팰리스3  서울특별시  강남구  도곡동  467-29  2004.0  2020-07-25  235.740  67   
2  1450000   타워팰리스3  서울특별시  강남구  도곡동  467-29  2004.0  2020-10-27  185.622  66   
3  1300000   타워팰리스3  서울특별시  강남구  도곡동  467-29  2004.0  2021-06-24  214.967  66   

     거래금액  
0  240000  
1  542500  
2  380000  
3  458000

In [109]:
os.listdir()

['APT_Detail_Seoul_2022.csv',
 'APT_Detail_Seoul_2022.xlsx',
 'APT_Merged.csv',
 'APT_Merged.xlsx',
 'APT_Price_Prep.z',
 'APT_Price_Seoul_2020.csv',
 'APT_Price_Seoul_2020_2022.csv',
 'APT_Price_Seoul_2020_2022.xlsx',
 'APT_Price_Seoul_2021.csv',
 'APT_Price_Seoul_2022.csv',
 'df1.csv',
 'df2.csv',
 'NA_Sample.xlsx',
 'pivot_table.xlsx',
 'price.csv']

In [110]:
detail = pd.read_excel('APT_Detail_Seoul_2022.xlsx')

In [111]:
detail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10290 entries, 0 to 10289
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   아파트ID   10290 non-null  int64  
 1   아파트명    10290 non-null  object 
 2   지번주소    10290 non-null  object 
 3   위도      10290 non-null  float64
 4   경도      10290 non-null  float64
 5   동수      10290 non-null  int64  
 6   세대수     10290 non-null  int64  
 7   임대수     10290 non-null  int64  
 8   용적률     10290 non-null  int64  
 9   건폐율     10290 non-null  int64  
 10  주차대수    10290 non-null  int64  
 11  건설사     9746 non-null   object 
dtypes: float64(2), int64(7), object(3)
memory usage: 964.8+ KB


In [112]:
detail.head()

아파트ID          아파트명                지번주소         위도          경도  동수   세대수   
0  146479         YH빌리지  서울시 강남구 개포동 1237-8  37.478247  127.046670   1    16  \
1  119219     개포래미안포레스트    서울시 강남구 개포동 1282  37.478448  127.054031  31  2296   
2  140057  개포비버리하임(도시형)  서울시 강남구 개포동 1193-5  37.474555  127.049412   2    29   
3  107513       개포상지리츠빌   서울시 강남구 개포동 176-1  37.487257  127.060199   1    18   
4    8928          개포자이    서울시 강남구 개포동 12-2  37.496437  127.077115   4   212   

   임대수  용적률  건폐율  주차대수        건설사  
0    0  297   59     9  (주)세담종합건설  
1  120  249   21  3961    삼성물산(주)  
2    0  199   57    30   (주)덕인컨스텍  
3    0  202   31    41    상지건영(주)  
4    0  250   18   502    LG건설(주)

In [114]:
len(set(price['아파트']) & set(detail['아파트명']))

2556

In [121]:
len(set(price['아파트']) - set(detail['아파트명']))

4045

In [115]:
len(set(price['주소']) & set(detail['지번주소']))

0

In [116]:
price['주소'].head()

0       서울특별시 종로구 필운동 254
1       서울특별시 종로구 사직동 9-1
2       서울특별시 종로구 내수동 167
3    서울특별시 종로구 내수동 110-15
4        서울특별시 종로구 내수동 95
Name: 주소, dtype: object

In [117]:
detail['지번주소'].head()

0    서울시 강남구 개포동 1237-8
1      서울시 강남구 개포동 1282
2    서울시 강남구 개포동 1193-5
3     서울시 강남구 개포동 176-1
4      서울시 강남구 개포동 12-2
Name: 지번주소, dtype: object

In [118]:
price['주소'] = price['주소'].str.replace('특별', '')

In [119]:
len(set(price['주소']) & set(detail['지번주소']))

6773

In [120]:
price['주소'].nunique()

7610

In [122]:
len(set(price['주소']) - set(detail['지번주소']))

837

In [124]:
lotto = np.random.choice(a = range(1, 46), size = 6, replace = False)
lotto.sort()
print(lotto)

[10 11 17 18 20 26]


In [128]:
np.random.seed(seed = 20230511)
for i in range(10):
    lotto = np.random.choice(a = range(1, 46), size = 6, replace = False)
    lotto.sort()
    print(lotto)

[13 26 30 35 37 44]
[14 22 27 36 43 45]
[ 6 19 20 27 29 37]
[ 3  9 24 26 28 44]
[ 9 14 24 32 34 45]
[ 3  6  9 11 22 31]
[ 7 10 13 15 34 40]
[ 5 11 22 29 36 42]
[ 4  5  6 21 37 40]
[ 6  7 21 30 31 45]


In [129]:
np.random.seed(seed = 1)

In [130]:
nums = np.random.choice(a = range(1, 5), size = 5)
nums

array([2, 4, 1, 1, 4])

In [131]:
nums = pd.Series(data = nums)
nums

0    2
1    4
2    1
3    1
4    4
dtype: int32

In [133]:
nums.duplicated(keep = 'first')

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [134]:
nums.duplicated(keep = 'last')

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [135]:
nums.duplicated(keep = False)

0    False
1     True
2     True
3     True
4     True
dtype: bool

In [136]:
dup = detail['지번주소'].duplicated(keep = False)
dup

0        False
1        False
2        False
3        False
4        False
         ...  
10285    False
10286    False
10287    False
10288    False
10289    False
Name: 지번주소, Length: 10290, dtype: bool

In [138]:
detail[dup].sort_values(by = ['지번주소'])

아파트ID                  아파트명                     지번주소         위도   
18       419                    대청           서울시 강남구 개포동 12  37.495077  \
19       483                 대치2단지           서울시 강남구 개포동 12  37.494658   
8       1303               개포주공6단지          서울시 강남구 개포동 185  37.488645   
9       1307               개포주공7단지          서울시 강남구 개포동 185  37.489561   
474      724                현대6,7차         서울시 강남구 압구정동 456  37.530219   
475    27498         현대65동(대림아크로빌)         서울시 강남구 압구정동 456  37.531534   
956      902               주공고층3단지        서울시 강동구 둔촌동 174-1  37.524232   
959      901               주공저층2단지        서울시 강동구 둔촌동 174-1  37.522661   
1325  133403            미사아름채(도시형)       서울시 강동구 천호동 452-15  37.538300   
1326  133402           미사아름채(주상복합)       서울시 강동구 천호동 452-15  37.538306   
1539  145243   에피소드수유838(민간임대,도시형)          서울시 강북구 수유동 740  37.637149   
1540  145240  에피소드수유838(민간임대,주상복합)          서울시 강북구 수유동 740  37.637120   
2569  123685           노들리안3(주상복합)      서울시 관악구 봉천동 1667-13  37.482185   
2568  123686            노들리안3(도시형)      서울시 관악구 봉천동 1667-13  37.482176   
2863      67                광장극동2차        서울시 광진구 광장동 218-1  37.543740   
2875      66                  극동1차        서울시 광진구 광장동 218-1  37.543391   
2902   25418                    MY        서울시 광진구 구의동 251-1  37.541632   
2903  120820               MY(도시형)        서울시 광진구 구의동 251-1  37.541662   
3077  123905             테라팰리스건대2차          서울시 광진구 자양동 860  37.538310   
3078  123902        테라팰리스건대2차(도시형)          서울시 광진구 자양동 860  37.538385   
3171  105912             화양타워(도시형)       서울시 광진구 화양동 110-37  37.546993   
3172   14620            화양타워(주상복합)       서울시 광진구 화양동 110-37  37.547038   
3157  119123                씨즈건대힐스          서울시 광진구 화양동 530  37.546204   
3158  116717           씨즈건대힐스(도시형)          서울시 광진구 화양동 530  37.546199   
3380  102801         하나세인스톤2차(도시형)         서울시 구로구 구로동 97-4  37.496566   
3381  110384        하나세인스톤2차(주상복합)         서울시 구로구 구로동 97-4  37.496620   
4175     263                    한신          서울시 노원구 하계동 284  37.637505   
4166   25841               청구(284)          서울시 노원구 하계동 284  37.638176   
4677  109130                 제이드파크       서울시 동대문구 장안동 382-2  37.569936   
4678  109134            제이드파크(도시형)       서울시 동대문구 장안동 382-2  37.569944   
4806  127262      이문휘경지웰에스테이트(도시형)         서울시 동대문구 휘경동 377  37.594720   
4807  126139     이문휘경지웰에스테이트(주상복합)         서울시 동대문구 휘경동 377  37.594722   
4808    3379                 주공1단지          서울시 동대문구 휘경동 57  37.583070   
4809  100207                 주공2단지          서울시 동대문구 휘경동 57  37.583287   
4916     374                    극동          서울시 동작구 사당동 105  37.491697   
4945     380               사당우성2단지          서울시 동작구 사당동 105  37.487604   
4946     381               사당우성3단지          서울시 동작구 사당동 105  37.490400   
4963     378                 신동아4차          서울시 동작구 사당동 105  37.490198   
5152  148586              라이프(도시형)       서울시 마포구 노고산동 54-21  37.555422   
5153  148587             라이프(주상복합)       서울시 마포구 노고산동 54-21  37.555422   
5676  132162      더스타일하우스디센트럴(도시형)       서울시 서대문구 충정로3가 480  37.561254   
5675  132163           더스타일하우스디센트럴       서울시 서대문구 충정로3가 480  37.561248   
6194  126357                 훼미리타운       서울시 서초구 방배동 932-34  37.484818   
6195  106897            훼미리타운(도시형)       서울시 서초구 방배동 932-34  37.484810   
7440    3754                  장미2차           서울시 송파구 신천동 11  37.520404   
7441     622                  장미3차           서울시 송파구 신천동 11  37.518535   
7433     620                    미성         서울시 송파구 신천동 17-6  37.517448   
7443    1284                   크로바         서울시 송파구 신천동 17-6  37.516403   
8868  109469           한남아이파크(도시형)          서울시 용산구 한남동 828  37.532332   
8869  109492          한남아이파크(주상복합)          서울시 용산구 한남동 828  37.532203   
8937  119075           만연샌텀시티(도시형)        서울시 은평구 갈현동 456-8  37.618499   
8938  119076          만연샌텀시티(주상복합)        서울시 은평구 갈현동 456-8  37.618508   
9231  140893          미래하임(229-40)       서울시 은평구 신사동 229-40  37.596794   
9232  14089

In [141]:
detail[detail['지번주소'].duplicated()].shape[0]

29

In [142]:
detail[~detail['지번주소'].duplicated()].shape[0]

10261

In [143]:
detail = detail[~detail['지번주소'].duplicated()]

In [144]:
detail.shape[0]

10261

In [145]:
set(price.columns) & set(detail.columns)

set()

In [146]:
pd.merge(left = price, right = detail, how = 'inner', 
         left_on = '주소', right_on = '지번주소')

아파트      시    구    동     지번  건축년도        거래일    전용면적   층   
0       신동아블루아광화문의꿈  서울특별시  종로구  필운동    254  2007 2020-01-03  111.97   6  \
1       신동아블루아광화문의꿈  서울특별시  종로구  필운동    254  2007 2020-02-21  108.95   7   
2       신동아블루아광화문의꿈  서울특별시  종로구  필운동    254  2007 2021-10-25  111.97   8   
3             세종로대우  서울특별시  종로구  내수동    167  1994 2020-01-06  109.91  11   
4             세종로대우  서울특별시  종로구  내수동    167  1994 2020-02-20   66.96  12   
...             ...    ...  ...  ...    ...   ...        ...     ...  ..   
132808        더메종건대  서울특별시  광진구  화양동   23-5  2022 2022-12-23   17.78  12   
132809     삼영N-CITY  서울특별시  은평구  응암동  96-19  2015 2022-12-24   45.91   6   
132810        길훈로즈빌  서울특별시  양천구  신정동   1297  2002 2022-12-16   84.95  14   
132811        길훈로즈빌  서울특별시  양천구  신정동   1297  2002 2022-12-19   84.95  14   
132812    강동리버스트4단지  서울특별시  강동구  강일동    114  2020 2022-12-29   59.99   7   

          거래금액  ...               지번주소         위도          경도  동수   세대수  임대수   
0       10.000  ...    서울시 종로구 필운동 254  37.575816  126.969968   1    28    0  \
1        9.600  ...    서울시 종로구 필운동 254  37.575816  126.969968   1    28    0   
2       14.000  ...    서울시 종로구 필운동 254  37.575816  126.969968   1    28    0   
3        8.800  ...    서울시 종로구 내수동 167  37.572764  126.973305   1    60    0   
4        6.150  ...    서울시 종로구 내수동 167  37.572764  126.973305   1    60    0   
...        ...  ...                ...        ...         ...  ..   ...  ...   
132808   2.585  ...   서울시 광진구 화양동 23-5  37.547571  127.067317   1    99    0   
132809   3.170  ...  서울시 은평구 응암동 96-19  37.601085  126.925963   1    18    0   
132810  11.600  ...   서울시 양천구 신정동 1297  37.522555  126.871307   1    49    0   
132811  11.600  ...   서울시 양천구 신정동 1297  37.522555  126.871307   1    49    0   
132812   5.500  ...    서울시 강동구 강일동 114  37.572611  127.173100  10  1239  597   

        용적률 건폐율  주차대수         건설사  
0       515  59    39  (주)신동아종합건설  
1       515  59    39  (주)신동아종합건설  
2       515  59    39  (주)신동아종합건설  
3       499  38   167        대우건설  
4       499  38   167        대우건설  
...     ...  ..   ...         ...  
132808  659  59    56         NaN  
132809  339  55    15    (전)신원아키텍  
132810  259  17    56   길훈종합건설(주)  
132811  259  17    56   길훈종합건설(주)  
132812  202  21  1154     (주)두산건설  

[132813 rows x 28 columns]

In [147]:
pd.merge(left = price, right = detail, how = 'outer', 
         left_on = '주소', right_on = '지번주소')

아파트      시    구    동   지번    건축년도        거래일    전용면적    층   
0          신동아블루아광화문의꿈  서울특별시  종로구  필운동  254  2007.0 2020-01-03  111.97  6.0  \
1          신동아블루아광화문의꿈  서울특별시  종로구  필운동  254  2007.0 2020-02-21  108.95  7.0   
2          신동아블루아광화문의꿈  서울특별시  종로구  필운동  254  2007.0 2021-10-25  111.97  8.0   
3       광화문스페이스본(106동)  서울특별시  종로구  사직동  9-1  2008.0 2020-01-02  163.33  2.0   
4       광화문스페이스본(106동)  서울특별시  종로구  사직동  9-1  2008.0 2020-06-22  150.40  7.0   
...                ...    ...  ...  ...  ...     ...        ...     ...  ...   
143400             NaN    NaN  NaN  NaN  NaN     NaN        NaT     NaN  NaN   
143401             NaN    NaN  NaN  NaN  NaN     NaN        NaT     NaN  NaN   
143402             NaN    NaN  NaN  NaN  NaN     NaN        NaT     NaN  NaN   
143403             NaN    NaN  NaN  NaN  NaN     NaN        NaT     NaN  NaN   
143404             NaN    NaN  NaN  NaN  NaN     NaN        NaT     NaN  NaN   

        거래금액  ...                 지번주소         위도          경도   동수   세대수  임대수   
0       10.0  ...      서울시 종로구 필운동 254  37.575816  126.969968  1.0  28.0  0.0  \
1        9.6  ...      서울시 종로구 필운동 254  37.575816  126.969968  1.0  28.0  0.0   
2       14.0  ...      서울시 종로구 필운동 254  37.575816  126.969968  1.0  28.0  0.0   
3       16.2  ...                  NaN        NaN         NaN  NaN   NaN  NaN   
4       14.6  ...                  NaN        NaN         NaN  NaN   NaN  NaN   
...      ...  ...                  ...        ...         ...  ...   ...  ...   
143400   NaN  ...   서울시 중랑구 중화동 326-46  37.596453  127.072348  1.0  10.0  0.0   
143401   NaN  ...    서울시 중랑구 중화동 293-9  37.598905  127.080854  1.0  18.0  0.0   
143402   NaN  ...      서울시 중랑구 중화동 457  37.599231  127.083003  6.0  66.0  0.0   
143403   NaN  ...  서울시 중랑구 중화동 309-106  37.604205  127.076350  1.0  15.0  0.0   
143404   NaN  ...   서울시 중랑구 중화동 318-81  37.597172  127.074593  1.0  19.0  0.0   

          용적률   건폐율  주차대수         건설사  
0       515.0  59.0  39.0  (주)신동아종합건설  
1       515.0  59.0  39.0  (주)신동아종합건설  
2       515.0  59.0  39.0  (주)신동아종합건설  
3         NaN   NaN   NaN         NaN  
4         NaN   NaN   NaN         NaN  
...       ...   ...   ...         ...  
143400  199.0  52.0   7.0   (주)지에스엠건설  
143401  194.0  55.0   9.0   신복종합건설(주)  
143402  195.0  56.0  47.0   명성종합건설(주)  
143403  199.0  54.0   9.0   강건종합건설(주)  
143404  199.0  47.0  20.0   (주)프름에씨앤씨  

[143405 rows x 28 columns]

In [148]:
pd.merge(left = price, right = detail, how = 'left', 
         left_on = '주소', right_on = '지번주소')

아파트      시    구    동      지번  건축년도        거래일    전용면적   층   
0          신동아블루아광화문의꿈  서울특별시  종로구  필운동     254  2007 2020-01-03  111.97   6  \
1       광화문스페이스본(106동)  서울특별시  종로구  사직동     9-1  2008 2020-01-02  163.33   2   
2                세종로대우  서울특별시  종로구  내수동     167  1994 2020-01-06  109.91  11   
3                 킹스매너  서울특별시  종로구  내수동  110-15  2004 2020-01-09  194.43   4   
4             경희궁파크팰리스  서울특별시  종로구  내수동      95  2003 2020-01-20  148.09   8   
...                ...    ...  ...  ...     ...   ...        ...     ...  ..   
139912           중앙하이츠  서울특별시  강동구  암사동  493-14  1998 2022-12-03   59.52   8   
139913         롯데캐슬퍼스트  서울특별시  강동구  암사동   414-2  2008 2022-12-06  111.22  10   
139914         선사현대아파트  서울특별시  강동구  암사동     509  2000 2022-12-10   59.64  17   
139915         파크뷰진도맨션  서울특별시  강동구  성내동   452-2  1996 2022-12-06  208.92  18   
139916       강동리버스트4단지  서울특별시  강동구  강일동     114  2020 2022-12-29   59.99   7   

         거래금액  ...                지번주소         위도          경도    동수     세대수   
0       10.00  ...     서울시 종로구 필운동 254  37.575816  126.969968   1.0    28.0  \
1       16.20  ...                 NaN        NaN         NaN   NaN     NaN   
2        8.80  ...     서울시 종로구 내수동 167  37.572764  126.973305   1.0    60.0   
3       13.00  ...  서울시 종로구 내수동 110-15  37.573307  126.970521   1.0    18.0   
4       14.90  ...      서울시 종로구 내수동 95  37.574236  126.970567   3.0   142.0   
...       ...  ...                 ...        ...         ...   ...     ...   
139912   5.30  ...  서울시 강동구 암사동 493-14  37.551240  127.131872   1.0   126.0   
139913  13.50  ...   서울시 강동구 암사동 414-2  37.556495  127.140819  40.0  3226.0   
139914   7.70  ...     서울시 강동구 암사동 509  37.552448  127.125871  16.0  2938.0   
139915  14.55  ...   서울시 강동구 성내동 452-2  37.527713  127.120842   1.0    18.0   
139916   5.50  ...     서울시 강동구 강일동 114  37.572611  127.173100  10.0  1239.0   

          임대수    용적률   건폐율    주차대수                 건설사  
0         0.0  515.0  59.0    39.0          (주)신동아종합건설  
1         NaN    NaN   NaN     NaN                 NaN  
2         0.0  499.0  38.0   167.0                대우건설  
3         0.0  273.0  49.0    49.0        (주)파라다이스건설산업  
4         0.0    0.0   0.0   329.0             삼성물산(주)  
...       ...    ...   ...     ...                 ...  
139912    0.0  278.0  30.0   137.0             (주)중앙건설  
139913    0.0  276.0  13.0  4596.0             롯데건설(주)  
139914    0.0  393.0  22.0  3012.0  현대건설(주), 현대산업개발(주)  
139915    0.0  394.0  32.0    35.0                 NaN  
139916  597.0  202.0  21.0  1154.0             (주)두산건설  

[139917 rows x 28 columns]

In [149]:
detail = detail.rename(columns = {'지번주소': '주소'})

In [150]:
set(price.columns) & set(detail.columns)

{'주소'}

In [151]:
apt = pd.merge(left = price, right = detail)

In [152]:
apt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132813 entries, 0 to 132812
Data columns (total 27 columns):
 #   Column  Non-Null Count   Dtype         
---  ------  --------------   -----         
 0   아파트     132813 non-null  object        
 1   시       132813 non-null  object        
 2   구       132813 non-null  object        
 3   동       132813 non-null  object        
 4   지번      132813 non-null  object        
 5   건축년도    132813 non-null  int32         
 6   거래일     132813 non-null  datetime64[ns]
 7   전용면적    132813 non-null  float64       
 8   층       132813 non-null  int64         
 9   거래금액    132813 non-null  float64       
 10  평당금액    132813 non-null  float64       
 11  거래년도    132813 non-null  int32         
 12  경과년수    132813 non-null  int32         
 13  거래월     132813 non-null  object        
 14  금액구간    132813 non-null  object        
 15  주소      132813 non-null  object        
 16  아파트ID   132813 non-null  int64         
 17  아파트명    132813 non-null  obje